### ISSUE TITLE
Adding a header on reproxy?

### ISSUE THREAD

**Issue by deweerdt** [h2o/h2o#1051]
When using a reverse proxy on `*`, it might be useful to distinguish between a request that's been reproxied by H2O and one that hasn't. What would be a good way to achieve that? Would a new `reproxy.header.add` directive, mimicked on `header.add` be a good way to do this?

**Comment by kazuho** [comment]
@deweerdt To me it seems that the issue cannot be solved by just adding headers in H2O, since a client can always send a request with the same header without connecting through H2O.

In other words, the most straightforward way to resolve the issue would be to test the source address of the connection within the server that receives requests either directly or through H2O.

**Comment by deweerdt** [comment]
That makes sense, thank you. Closing
