### ISSUE TITLE
h2 pushes: support rel=push

### ISSUE THREAD

**Issue by deweerdt** [h2o/h2o#1057]
H2O currently uses `rel=preload` in order to trigger pushes, "preload" is however something that already means something to the browser. In order to clarify that the intention is to push, we could use a distinct relation.
I thought that one way to address that would be to make `http2-push-preload` accept `ON`, `OFF` or `RELPUSH`. `ON` and `OFF` would retain the same semantics as today, but `RELPUSH` would look for `rel=push` instead of `rel=preload`. Alternatively, i thought we could make the directive accept a string in addition to accept a boolean, but it feels that this would be too flexible with little advantage.
Any thoughts?

**Comment by kazuho** [comment]
For the matter, I think we should follow what the spec. says (or is going to say). Having a non-standard way would cause confusion among the users in the long term.

Current version of [the preload draft](https://github.com/w3c/preload) suggests that `rel="preload"` with `nopush` attribute should be used as an indication to _not_ push a resource file over HTTP/2.

That said, it is true that there have been people arguing to _not_ use rel=preload as a push indicator; please refer to the discussion on the issues of the repository.

But personally, I do not think we have a need for distinguishing push and browser preload, with cache-digests (a.k.a. casper) and #873 there would no longer be performance penalties for pushing too much.

**Comment by deweerdt** [comment]
Hello @kazuho, thanks for your reply. When you point out that there was an existing discussion about the matter, I believe that you might be referring to https://github.com/w3c/preload/issues/38 followed by https://github.com/w3c/preload/pull/54 is that so? Please let me know if there's another resource that i should read on the matter.

It seems to me that when the question of opt-in vs out-out came out, as here: https://github.com/w3c/preload/pull/54#issuecomment-177021957 , the fact that pushes might actually worsen load times, as outlined in ["Experiences with HTTP/2 server push"](https://groups.google.com/a/chromium.org/forum/#!topic/loading-dev/RrmbwryJhXg) wasn't considered. That means two things:
- we could actually worsen load times for existing pages that use preload today for http/1
- we can't really use the advice given in the above paper, namely "Use server push to fill the initial cwnd and consider using preload links to reveal the remaining critical or hidden resources", at least not with headers.

Is that a fair assessment? If so, do you reckon i should open an issue with https://github.com/w3c/preload bringing this up?

**Comment by kazuho** [comment]
@deweerdt 
> When you point out that there was an existing discussion about the matter, I believe that you might be referring to w3c/preload#38 followed by w3c/preload#54 is that so? Please let me know if there's another resource that i should read on the matter.

You are correct that they are the relevant issues.

I'd also assume that people involved in the discussion would also aware of the "Experiences with HTTP/2 server push" document (and related discussion on the HTTPWG mailing list, starting [here](https://lists.w3.org/Archives/Public/ietf-http-wg/2016JulSep/0374.html)) as well as https://github.com/HTTPWorkshop/workshop2016/blob/master/talks/server-push.pdf.

My take against Google's document is that the issues have almost been solved in H2O.

The advice: "Use server push to fill the initial cwnd and consider using preload links to reveal the remaining critical or hidden resources" is under the premise that a server cannot switch to sending a response to a pulled request of higher priority while pushing another asset.

But with #873 enabled, the assumption no longer holds. H2O switches to sending a response to a new stream immediately.

The only remaining issue is browsers not sending PRIORITY frames for pushed streams as discussed in my responses to the HTTPWG mailing list thread. But I am not sure how much it affects the user experience in practice.

**Comment by deweerdt** [comment]
> I'd also assume that most people involved in the discussion are already aware of the "Experiences with HTTP/2 server push" document (and related discussion on the HTTPWG mailing list, starting here) as well as https://github.com/HTTPWorkshop/workshop2016/blob/master/talks/server-push.pdf.

I agree, i was merely pointing out that at the time of the discussion it didn't seem like the 'push can be harmful' side of the argument had played a big role, so it might be legitimate to re-open the discussion now that it's better understood.

> My take against Google's document is that the issues have almost been solved in H2O.

I agree to a large extent. The document shows however that what's pushed needs to be closely tailored to http/2, something that might not be the case for existing applications that used `preload` in http/1. In those cases, we might see a regression when switching to http/2, and it might not be practical to upgrade the application at the same time that the protocol on the server is changed.

Another case that came to mind, where push might differ from preload is when the origin wants to push to the edge, but not to the browser - possibly when the object is large, for fear of evicting other resources from the cache.

**Comment by kazuho** [comment]
> I agree, i was merely pointing out that at the time of the discussion it didn't seem like the 'push can be harmful' side of the argument had played a big role, so it might be legitimate to re-open the discussion now that it's better understood.

Thank you for the clarification.

_My_ position is that since preload can be a good indication to a HTTP/2 server to push a resource it would be better to adjust the servers (and clients) rather than trying to optimize the specification for incompetent implementations, and that H2O is already doing quite well (with the presumption that a TLS terminator is not used between the client and the server; anything that buffers above TCP between the HTTP/2 endpoints would be introcude HoB issues regardless of whether if push is used).

But reconsidering this, I might agree to have a separate indicator for H2 push for deployments that are impossible to immediately have both #873 and casper / cache-digests turned on.

> The document shows however that what's pushed needs to be closely tailored to http/2, something that might not be the case for existing applications that used `preload` in http/1.

I think it would be more valuable to discuss what the obstacles are and how they could be fixed, rather than jumping on to the conclusion that preload and H2 push should be indicated in distinct ways.

Let's look at the five rules proposed by the document how they apply to us.

"Rule 1: Push Enough to Fill Idle Network Time, and No More" does not apply to us (when not using a TLS terminator) thanks to #873.

"Rule 2: Push Resources in the Right Order" is handled mostly correctly thanks to [our prioritization of pushed responses based on their content-type](https://h2o.examp1e.net/configure/http2_directives.html#http2-reprioritize-blocking-assets). We might have a small portion of resources prioritized higher than they should be (e.g. a pushed script that is used with `<script async>`), or lower (e.g. a image that blocks rendering). Such mis-prioritization cannot be completely solved until clients start sending PRIOTIRY frames for reprioritizing pushed streams, though [critical](https://github.com/w3c/preload/issues/66) may help us.

"Rule 3: Don’t Push Resources the Client has Already Cached" is handled by casper / cache-digests (for which we have [a ServiceWorker-based implementation](https://github.com/h2o/cache-digests.js)).

"Rule 4: Use the Right Cookies" I think this is an interesting point. In our current implementation, we do not copy the cookie header from the parent request (nor the set-cookie header from the parent response) when a push is initiated. And once the browser sees a `PUSH_PROMISE` frame for the pushed response, it would unconditonally use _that_ response, even when we send `RST_STREAM` right afterwards.

Personally, I think a client _should_ initiate a pull when a pushed response that it intended to use got closed before the `HEADERS` frame. And I _think_ it might be the right moment to propose such guideline, now that the IETF working group on the mailing list is trying to find out the details on how clients / servers should handle push.

"Rule 5: Consider Preload Instead of Push" is not a discussion of a push-related issue.

**Comment by kazuho** [comment]
PS. I've posted my points to the mailing list :) https://lists.w3.org/Archives/Public/ietf-http-wg/2016JulSep/0553.html

**Comment by deweerdt** [comment]
https://github.com/h2o/h2o/pull/1169 is a better way to address the issue, closing
