### ISSUE TITLE
client OCSP stapeling error when OCSP gets disabled

### ISSUE THREAD

**Issue by Lennie** [h2o/h2o#1102]
Just had a error connecting to a HTTPS-website running on H2O with a browser (Firefox):

h2o version 1.7.3
OpenSSL: LibreSSL 2.2.7

In the error.log it said:

"[OCSP Stapling] disabled for certificate"

openssl s_client -host hostname -port 443 -status gave me this information:
# OCSP response:

OCSP Response Data:
    OCSP Response Status: successful (0x0)
    Response Type: Basic OCSP Response
    Version: 1 (0x0)
    Produced At: Jul  3 23:07:31 2016 GMT

```
Cert Status: good
This Update: Jul  3 23:07:31 2016 GMT
Next Update: Jul 10 23:07:31 2016 GMT
```

So it seems the server still sends an OCSP response even if they aren't being updated ? Shouldn't the server not send an old expired OCSP response ?

After a restart of H2O s_client gives me the new info:

```
This Update: Oct  4 06:06:25 2016 GMT
Next Update: Oct 11 06:06:25 2016 GMT
```

And browsers can connect again.

**Comment by Lennie** [comment]
Just to make it clear: I think h2o should not send outdated OCSP-responses to clients.

**Comment by kazuho** [comment]
Nice catch!

Looking at the relevant switch block (https://github.com/h2o/h2o/blob/master/src/main.c#L316-L342), it seems that the cached OCSP response is removed when the OCSP client returns a permanent failure (note: the cached response _is_ removed when OCSP stapling gets turned off due to repetitive temporary failures).

The issue will be fixed in the next release.

**Comment by kazuho** [comment]
@Lennie I believe that the issue has been fixed in the PR above, which has now been merged to master.

Please let us know if the problem persists.
