### ISSUE TITLE
more advanced logging

### ISSUE THREAD

**Issue by yannick** [h2o/h2o#1133]
we need to build a more advanced logging system where we are able to e.g. dump all headers in their original order or possibly even do minimal calculations/filtering. also escaping and formatting (e.g. json) is a constant topic.

currently we have added kafka as logging  endpoint (  https://github.com/tamediadigital/h2o/pull/1 ) which is already working nicely. 

now the next step would be to be able to log json data that is escaped and also able to get access to a few more internal variables. 
the question are:
- would you accept a PR in that direction
-  suggestions on how to implement it:
    logging via mruby handler ? adding new format strings for escaping and looping ? special json formatter?

**Comment by kazuho** [comment]
@yannick Thank you for opening the discussion. And it's great to know that H2O is working well in your environment.

I would be more than happy to see a PR, but it might be better to discuss how we should solve the issue beforehand so that you could concentrate on developing a feature that can be maintained upstream.

Regarding the issues, for JSON, the logging functions used by the access logger is already capable of emitting JSON-style ecsapes. The functions defined in lib/core/logconf.c is shared between the access logger and the status handler. The latter uses logconf to build JSON objects. I believe that we could naturally add an attribute to the `access-log` configuration directive for specifying the escape method.

Also, creating a directive for dumping all the headers in the order they arrived, and having them emitted as a single JSON string makes sense me.

OTOH, it would be great if you could elaborate the way you are interested in controlling the logging using mruby. At the moment, I am rather negative about introducing conditional operators to the access log directives. I think we should share what we want to achieve before going down to discussing how we can implement such feature.

**Comment by yannick** [comment]
@kazuho thanks for taking the time and i agree it needs to be discussed and thats why i opened the issue in the first place.
i also think introducing conditional operators isn't a very clever thing to do, i just wanted to list a few options. 

the json escaping and capability i've overlooked so far, let's look into this @9il and then get back with a proposal. 

the reason/rationale behind  doing it in mruby would be additional flexibility to enhance the log directly there with additional data such as device detection (see e.g. https://github.com/51Degrees ) 

another advanced logging feature would be adding a start and end-of session log whenever the TCP/TLS connection establishes and closes. there you would log timings (session duration) and other tcp options similar to e.g. $tcpinfo_rttvar in nginx.

**Comment by kazuho** [comment]
@yannick 
> the reason/rationale behind doing it in mruby would be additional flexibility to enhance the log directly there with additional data such as device detection

Agreed.

There could be various hacks to accomplish this, but I think the best way would be to add a logging directive to log environment variables set by mruby. At the moment, there is [a backdoor for setting environment variables from mruby](https://github.com/h2o/h2o/blob/v2.1.0-beta3/lib/handler/mruby.c#L599-L606), however, [logging of the variables is limited to `REMOTE_USER`](https://github.com/h2o/h2o/blob/v2.1.0-beta3/lib/core/logconf.c#L570-L575).

We should extend the logger so that it can be used to log arbitrary variables (the format specifier should follow the convention of the Apache HTTP server).

> another advanced logging feature would be adding a start and end-of session log whenever the TCP/TLS connection establishes and closes. there you would log timings (session duration) and other tcp options similar to e.g. $tcpinfo_rttvar in nginx.

We already have some format specifiers to log TLS attributes, the connection ID, and the time spent since the connection was established. The thing that might be missing is a way to log the disconnection timing.

I am generally supportive to adding a hook to the access logger that can be used for log TCP / TLS connection timings.

**Comment by yannick** [comment]
this can be closed:
- logging of session-id is implemented
- logging of arbitrary env vars is implemented
