### ISSUE TITLE
h2o on FreeBSD

### ISSUE THREAD

**Issue by bax-** [h2o/h2o#1157]
FreeBSD still only has 2.0.4 in the ports tree.
Is there anyone willing to administer a h2o-current port or is it known when the FreeBSD port will be updated?
Thank you!

**Comment by utrenkner** [comment]
The port maintainer @dch has [explained the situation](https://github.com/h2o/h2o/issues/1144#issuecomment-269222627) a week ago. He ported the fix for CVE-2016-7835 (available in ports as [2.0.4_2](https://svnweb.freebsd.org/ports?view=revision&revision=429910), since end of December) but had problems with adapting the port to 2.0.5. I am sure he would appreciate any help with getting a 2.0.5 port working on FreeBSD. 

Of course, I would love to see a new port h2o-dev with the latest 2.1.0-beta release. But I do not have the time and even if I had, I would rather help Dave with getting the latest stable version ported.

**Comment by dch** [comment]
FWIW the specific issue with 2.0.5 is that the installation tries to retrieve files from the internet during the build process, which is a no-no for repeatable builds inside the FreeBSD ports framework, for the mruby update. I don't yet understand how this works, but I'll have a look at this soon with @kazuho to work it out.

**Comment by kazuho** [comment]
The issue has been fixed in #1149, and I have released [version 2.0.6](https://github.com/h2o/h2o/releases/tag/v2.0.6) that includes the fix.

@dch Could you please try building 2.0.6? Thank you for all your efforts.

**Comment by dch** [comment]
\o/ works here! https://pkg.skunkwerks.at/poudriere/build.html?mastername=11_amd64-default&build=2017-01-06_08h58m38s I have a couple of ports-specific issues to deal with but this should land soon, at least in trunk ports.

**Comment by hbowden** [comment]
If people need help with the FreeBSD port I can help. I am pulling h2o into my project and FreeBSD support is an absolute must have.

**Comment by dch** [comment]
@hbowden can you contact me via email to discuss? see my github profile for address

**Comment by hbowden** [comment]
@dch I just sent you an email.

**Comment by Varbin** [comment]
When 2.1.0 will be in ports?

**Comment by dch** [comment]
On Sun, 12 Feb 2017, at 17:54, Varbin wrote:
> When 2.1.0 will be in ports?

Quite soon, the patch is already submitted. This took a while as I
needed to remove how we handle SSL - it was not actually possible to use
bundled SSL at all as either the system or the ports tree SSL is always
picked up by default.

**Comment by dch** [comment]
if there's interest in having a freebsd-devel built off master  in ports, contact me privately `@freebsd.org` if there's enough interest I'll add it in.
