### ISSUE TITLE
2.2.0-beta1: TLS 1.3 is not working with ECDSA certificate

### ISSUE THREAD

**Issue by csmk** [h2o/h2o#1211]
When I try to connect, I keep getting this in H2O' error.log:

```
received fatal signal 11
worker 6478 died unexpectedly with status:11, restarting
starting new worker 6519
/usr/bin/h2o[0x4aa6fe] neverbleed_init at ??:?
/lib64/libpthread.so.0(+0x10f50)[0x7f2272777f50] ?? ??:0
[INFO] raised RLIMIT_NOFILE to 8192
h2o server (pid:6519) is ready to serve requests
received fatal signal 11
/usr/bin/h2o[0x4aa6fe] neverbleed_init at ??:?
/lib64/libpthread.so.0(+0x10f50)[0x7f513f56af50] ?? ??:0
fetch-ocsp-response (using LibreSSL 2.5.1)
sending OCSP request to http://ocsp.int-x3.letsencrypt.org/
/foo/bar/something/something.crt: good
        This Update: Feb 27 14:00:00 2017 GMT
        Next Update: Mar  6 14:00:00 2017 GMT
verifying the response signature
verify OK (used: -VAfile /tmp/alcu6uraw1/issuer.crt)
new worker 6519 seems to have failed to start, exit status:11
starting new worker 6536
```

It work fine if I disable the TLS 1.3 flag (#ssl-version-max) on Chromium 56.

Also, as because I use ECDSA and don't have openssl >= 1.1.0, neverbleed is deactivated. Don't know why the log keep mentioning about neverbleed. This is somehow related?!

**Comment by csmk** [comment]
The same occur with Firefox 51+NSS 3.29.1 and curl+NSS.

**Comment by kazuho** [comment]
Thank you for reporting the issue. I will look into if we can fix the issue.

Details: it seems that we are failing to setup an ECDSA key for picotls (`ptls_openssl_init_sign_certificate` is returning error at [src/main.c line 504](https://github.com/h2o/h2o/blob/v2.2.0-beta1/src/main.c#L504)). However since there is no error check being done here, an broken context gets set up for picotls that leads to a SEGV during TLS 1.3 handshake.

**Comment by csmk** [comment]
> it seems that we are failing to setup an ECDSA key for picotls

Yes, you're right. I just tried with a RSA certificate and all clients above are _speaking_ TLS 1.3.

**Comment by kazuho** [comment]
@csmk I think that we have fixed the issue now that the PR above has landed, under the assumption that you are using either secp384r1 or sep521r1.

If you are have a EC PARAMETER that specifies the parameters explicitly (instead of using a _named_ curve, that specifies the parameters using names), then you are out of lack; unnamed curves are not supported in TLS 1.3. In that case, you would see a warning in the error log that TLS 1.3 is disabled.

**Comment by csmk** [comment]
Yay!! Everything is good now. :smiley: 

Much obliged for your assistance and fast response.

いつもお世話になりありがとうございます。:bowing_man:
