### ISSUE TITLE
Disable priorities in H2O server

### ISSUE THREAD

**Issue by user963** [h2o/h2o#1373]
Hi,
I want to disable the priorities and weights in the h2o server. I want that the server reply to the requests respecting the dependencies but without sharing the available resources between many streams at the same time.  
Is it possible to do this test with h2o server ?

**Comment by deweerdt** [comment]
If the client uses exclusive dependencies, H2O will schedule the resources in such a way that priorities are ignored. That's essentially what Chrome does.

**Comment by user963** [comment]
Thank you for your response,
I need to use dependencies between the streams for real dependencies between them.
![capture du 2017-07-18 10-22-40](https://user-images.githubusercontent.com/29480111/28307442-33a6c22a-6ba3-11e7-943d-fc8b3b71246f.png)
For example if i have this dependency tree , when Stream 2 (S2) is totally sent, the server must send all the stream 3 (S3) then all the stream 4 (S4) and don't share resources between them.

**Comment by kazuho** [comment]
Unfortunately, there is no knob to change the behavior in such a way.

I believe that the easiest way to change the behavior in such a way would be to modify the processing of the PRIORITY frame in lib/http2/connection.c, so that the PRIORITY frame would be recognized by h2o in the way you like (i.e. `S4` depends on `S3`).
