### ISSUE TITLE
Possible to modifying request header (e.g. with mruby)?

### ISSUE THREAD

**Issue by utrenkner** [h2o/h2o#1376]
Because I need a quick solution to [this issue](https://github.com/h2o/h2o/issues/1375). I would like to strip the ``If-Modified-Since`` header from certain requests. Is this possible in the h2o configuration, or via a mruby handler?

**Comment by utrenkner** [comment]
Found a different quick-fix for the specific problem: I set the modification date of all PHP files to 1 year in the future, hoping that the problem will be resolved by then.

Nevertheless, I would still be interested in an answer for how to modify the request header...

**Comment by kazuho** [comment]
Thank you for asking the question! #1217 will provide the feature.

**Comment by marty90** [comment]
Does not work for me :(
`if-modified-since` and `last-modified` are both in the future (at the same future date that I have set). Thus, it triggers a 304 response :(

**Comment by i110** [comment]
@marty90 WHAT doesn't work for you? can you show me your configuration?

**Comment by marty90** [comment]
I had the same problem: I wanted to prevent 304 responses. I tried the solution here proposed. I set a the modification date of files to 1 year in the future. Unfortunately this did not work for me. In the HTTP responses `last-modified` header has the same date of `if-modified-since` header in the requests that revalidate the objects; thus I get a 304 response again.
However, I solved by putting:
```
header.set: "Last-Modified: Fri, 06 Apr 1999 15:47:10 GMT"
```
in the H2O configuration file, that artificially changes the `last-modified` to sometimes in the past.
