### ISSUE TITLE
Internal Redirect and HTTP/2 Push 

### ISSUE THREAD

**Issue by laugere** [h2o/h2o#1424]
Hi,

I hope I am not making you waste your time if this is silly, but I have a question regarding HTTP/2 Push.

I have a PHP script (index.php) which adds the header :

`Link: </ui.js>; rel=preload; as=script`

When the script is invoked directly : `https://xxxx.xxx/index.php`, the resource "ui.js" is pushed correctly. 

If the script is invoked through a redirect :

```
"/":
    file.dir: xxxx            
    redirect:
        url: /index.php/
        internal: YES
        status: 307
```

"ui.js" seems to no longer be "pushed" (the "preload" works)

I guess it's a matter of authority as mentioned here : https://github.com/h2o/h2o/issues/860

It works if the script adds the header with a full URL :

`Link: <https://xxxx.xxx/ui.js>; rel=preload; as=script`

So I was wondering if this is the expected behavior/requirement? 

Also, about CASPer, I tried to understand the sources, but this is beyond my skill, so I was wondering :

- does CASPer take in consideration the last modified time of a file? In other words, let's say the file "ui.js" has been pushed once to the client, the next times, it will not, because CASPer is aware the file has already been pushed, but what happens if the file is modified in the meantime, will CASPer push the new version?

- is it possible to disable CASPer on a file by file basis? For example, let's say I want to push a .css file which has always the same content, and a .js which is dynamically generated in PHP, and which has part of its content changing each time it's requested. Is it possible to have the .css to use CASPer, and NOT this .js file?

- if I don't make mistakes, the expiration date of the CASPer cookie is hard coded, would it make sense to add an option, so we can choose how long we want the cookie to last including having the cookie to live only for the time of the browser session ?

Thank you,

ps: "h2o version 2.3.0-DEV"

**Comment by kazuho** [comment]
Sorry for the belated response.

I believe that the cause of the issue is due to a mismatch in the authority (i.e. the hostname part of the URL) supplied by the client and what is specified in h2o.conf.

Consider the case where you have a configuration like follows.

```
hosts:
  example.com:
    paths:
      file.dir: /path/to/docs
      redirect:
        url: /index.php/
        internal: YES
        status: 307
```

When client accesses the server with URL: `https://example.org/` (notice that the hostname is different from what is specified in the `hosts` section) and internal redirect using a relative URL (i.e. `/index.php/`) happens, the URL being fetched after the internal redirect becomes `https://example.com/index.php/`. This is because internal redirect using relative URL happens in the context of the configuration (hence the value in the `hosts` section is used).

The PHP script then sends out `link: </ui.js>; ...`, which is interpreted by H2O as `https://example.com/ui.js`.

The server then detects that the URL of the js file does not belong to the same authority that _the client is accessing_, and decides not to push.

So you should either set the value of the `hosts` section to what the hostname supplied by the client, or (as you have found out) use an absolute URL in the link header.

**Comment by laugere** [comment]
Thank you.
