### ISSUE TITLE
#task raises FiberError in #initialize method

### ISSUE THREAD

**Issue by tagomoris** [h2o/h2o#1536]
When I used the top-level method `#task` (added for async processing w/ H2O::Channel) in `#initialize` method of classes defined by me, `FiberError` with message "can't cross C function boundary" was raised.

```
h2o server (pid:31089) is ready to serve requests
Unexpected error FiberError:can't cross C function boundary
	(eval):8:in _h2o__run_child_fiber
	(eval):84:in task
	test/h2o/frontend.conf:11:in initialize
	test/h2o/frontend.conf:19:in eval
	(eval):41
```

The minimum code & configuration is here: https://gist.github.com/tagomoris/ae068d7b2380095ab5e721d8c0b219d6

I'm not sure that it is just limitation of `task` and mruby (and I took a mistake against it), or an unexpected bug of h2o (or mruby?).
Could you take a look on this?

**Comment by tagomoris** [comment]
And it is a bit confusing that `#task` (and some other definitions) are introduced via `eval`.
This project has a dependency of `mruby-require`, so it seems possible to use it to load definitions written in ruby.

**Comment by kazuho** [comment]
The issue can only be solved on mruby-side. Until the issue gets resolved (assuming that it would be considered as a bug of mruby), the workaround would be to call `task` in a non-constructor method.

> This project has a dependency of `mruby-require`, so it seems possible to use it to load definitions written in ruby via functionality of `mruby-require`, not eval.

Generally speaking, we refrain from loading code dependent to a specific version of h2o from a file, to avoid confusion caused by loading a file that corresponds to an wrong version.

Does that make sense to you? Or if you have any specific reason to have the definition stored in a separate file, please let us know.

**Comment by tagomoris** [comment]
About Fiber, I understood your point. For now, I will move code to call `#task` (and other Fiber-related code possibly) from `#initialize` to other place to help this issue.

About `eval`: I can understood your points. And based on it, we can improve the backtrace readability of these methods. (I'll create another pull-request about it, anyway.)

**Comment by tagomoris** [comment]
I created a pull-req #1537 for backtrace of embedded mruby code.
