### ISSUE TITLE
Latency Redis and http_request

### ISSUE THREAD

**Issue by proyb6** [h2o/h2o#1700]
Is there anyway I could reduce the latency?

Load url directly on Google Chrome took an average of 200ms:
http://www.example.com

When storing the page in Redis, it took an average of 500ms to display the contents:
```
      "/test":
        mruby.handler: |
          r = H2O::Redis.new(:host => '127.0.0.1', :port => 6379)
          proc {|env|
             c = r.get("example").join
             if c.nil?
               s, h, c = http_request("http://www.example.com").join
               r.set("example", c, {:ex => 90})
             end
             [s, h, c]
          }

```

**Comment by i110** [comment]
@proyb6 Sorry for belated response. I found that 
```ruby
r.set("example", c, {:ex => 90})
```
is wrong syntax. The 3rd argument should be `90`, not hash value (see: [redis SET command](https://redis.io/commands/set)). All of H2O::Redis methods have arguments which are exactly conformant with original redis commands.

Thus your code doesn't cache the content at all, and fetch it from example.com everytime. You can catch the syntax error by doing like this:
```ruby
begin
  r.set("example", c, {:ex => 90}).join
rescue => e
  p e
end
```
But as you see it has to `join` (i.e. wait the response from redis server), which may causes some performance degradation.

By the way your code is also wrong because `s` and `h` will be nil if the cached content was found. Do the thing like
```ruby
if c.nil?
  s, h, c = http_request("http://www.example.com").join
  r.set("example", c, {:ex => 90})
else
  s, h, c = [200, {}, [c]]
end
```

**Comment by proyb6** [comment]
@i110 Great thanks, but I'm confuse 
```The 3rd argument should be 90```

I think ```{:ex => 90}``` is still a hash value in your code example?

**Comment by i110** [comment]
@proyb6 

> I think {:ex => 90} is still a hash value in your code example?

Which example?

**Comment by proyb6** [comment]
No worries, will try some day.

**Comment by proyb6** [comment]
@i110 I have a go on your code but output is completely different 

```
    "/e":
      mruby.handler: |
        r = H2O::Redis.new(:host => '127.0.0.1', :port => 6379)
        proc {|env|
          c = r.get("example").join
          if c.nil?
            s, h, c = http_request("http://www.example.com").join
            r.set("example", c, 90)
            s, h, c = [200, {}, [c]]
          else
            s, h, c = [200, {}, [c]]
          end
        }
```

Output
```#<H2O::HttpInputStream:0x1253268>```

Using back ```[s, h, c]``` seem working, still slower at 500ms+ on first load and subsequent browser page reload.

Redis-cli don't seem to store any cache of the "example" page
```KEYS *```
