### ISSUE TITLE
Yah JSON streaming paraer

### ISSUE THREAD

**Issue by proyb6** [h2o/h2o#1705]
It took me only recently saw this benchmark in lH2O use yajl libraries. What is the difference between MRuby-json and theirs?

**Comment by proyb6** [comment]
@yannick

https://gist.github.com/eirc/1300627/89d1fcfde7a4a9cb56e174415c0ed401e7ad8eec

And TechEmpower I think you seen they  code:
https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/C/h2o/src/request_handler.c


MessagePack is still the fastest?

**Comment by proyb6** [comment]
On the other hand, OJ seem faster than Yajl:
https://github.com/ohler55/oj/blob/master/README.md

And JSON pusher is something interesting:
http://www.piperpushcache.com/

**Comment by proyb6** [comment]
Sorry, a missing benchmark to Yajh vs Oj 

https://github.com/mipearson/jsontest/blob/master/README.md

**Comment by volyrique** [comment]
@proyb6 The TechEmpower Web framework benchmarks source code you link to is a C application, so all the Ruby-based parsers you are referring to are not applicable to it (and vice versa).

Actually, I implemented that code, and the reason I chose YAJL was because I was familiar with it (used it for other projects before), and I liked its design. From a performance point of view it seems to be doing a reasonable job, although I suspect that if I switch to one of the JSON generators used by the other C benchmarks, I might get better results.
