### ISSUE TITLE
Silicon libh2o backend

### ISSUE THREAD

**Issue by matt-42** [h2o/h2o#171]
Hello,

I am developing Silicon [1], a C++ web framework using compile time meta
programming to implement near-zero cost abstractions.

Since libh2o supports a nice range of protocols with good performances, It would
be interesting to wrap it as a silicon backend. I read the simple.c example and I have 3 questions:

   - For performances, do you recommend libuv or the h2o event loop?
   - How can we scale the server on multiple cores?
   - How can we access the request body ? Their is a post example in simple.c
     but it does not read the post data in the body.

Update: The response to the 3rd question is here: https://github.com/h2o/h2o/issues/92

[1] http://siliconframework.org/

**Comment by kazuho** [comment]
@matt-42 Thank you for looking into H2O.  It would be great if you could support it in Silicon.

> * For performances, do you recommend libuv or the h2o event loop?

The answer depends on how Silicon is designed.  Is my understanding correct that the handlers of Silicon run synchronously (i.e. do they block until they gather all the data)?  If that is the case, using either would be fine.  Besides, it might be a good idea to create a wrapper that dispatches the requests to a different thread that runs the Silicon handlers, since H2O is a event-driven server.

If it is the case that Silicon has an async mode, I would suggest using libuv, since it is popular and has various async bindings (see https://github.com/libuv/libuv/wiki/Projects-that-use-libuv).

> * How can we scale the server on multiple cores?

By default, H2O dispatches worker threads equal to the number of CPU cores.

> * How can we access the request body ? Their is a post example in simple.c but it does not read the post data in the body.

It does :-) `req->entity` holds the request body. (see also https://github.com/h2o/h2o/issues/92)

**Comment by matt-42** [comment]
Silicon procedures run synchronously. Async procedures could be added in the future but I'm waiting for gcc and clang to implement [resumable functions](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4134.pdf) (async/await keywords) which greatly simplify async programming. 

Thanks, req->entity and h2o_send is pretty much all I need.
