### ISSUE TITLE
Incomplete instructions on how to install/use libh2o

### ISSUE THREAD

**Issue by informer2000** [h2o/h2o#173]
I have successfully managed to build and install libh2o on both Ubuntu Linux and Yosemite. However, I'm having problems compiling the `simple.c` example.

One problem that is common to both platforms is missing headers from the klib and picohttpparser dependencies. Trying to build/install those libraries, I was not able to find instructions on how to do so. The Makefile for picohttpparser seems to just build the test. And klib does not include any build files.

Since libh2o is statically built, I assume I just need to copy the header files from both libraries to `/usr/local/include` or `/usr/include`.

I had another issue when attempting to compile one of libuv headers with either gcc or clang. The compiler complains about a conflicting types for the inline function `uv_tty_set_mode()` in `uv.h`.

**Comment by kazuho** [comment]
Thank you for reporting the issue.

Agreed that it is a problem (relates to #96 #63).  I will consider how the header files can be installed (as well as adjusting libh2o.a so that it would not conflict with other libraries using picohttpparser).

For the mean time, I suggest adding the necessary paths (`deps/klib` and `deps/picohttpparser` below the H2O root) to the include paths of your compiler.

> I had another issue when attempting to compile one of libuv headers with either gcc or clang. The compiler complains about a conflicting types for the inline function uv_tty_set_mode() in uv.h.

Sounds like a libuv issue (as the function is not used in h2o).  Please refer to the issues of https://github.com/libuv/libuv

**Comment by kazuho** [comment]
Closing the issue as it is mostly fixed in #174 (please read the comments to find out the details).

Please feel free to reopen the issue if the problem persists.

**Comment by informer2000** [comment]
I managed to get rid of of the libuv related error by adding `-DH2O_USE_LIBUV=0` when building the example. I'm not sure if H2O is actually using libuv anymore. I believe that there was a post on your blog about this. Yet, although the CMakeLists.txt file does not use it in the build target, it checks to make sure it is there when installing. 

I'm also getting a couple errors for two const variables defined in `http2.h`:

```
error: default initialization of an object of const type 'const h2o_http2_settings_t' (aka 'const st_h2o_http2_settings_t') requires a user-provided default constructor

error: default initialization of an object of const type 'const h2o_http2_settings_t' (aka 'const st_h2o_http2_settings_t') requires a user-provided default constructor
```

I believe they are missing the `extern` keyword.

**Comment by informer2000** [comment]
I should also add that I'm now getting a *no matching function for call to* error for the calls to `h2o_evloop_socket_create()` and `h2o_http1_accept()` and `h2o_accept_ssl`. Looking into the corresponding header files, one argument seems to be missing for each of the aforementioned calls.

**Comment by kazuho** [comment]
@informer2000 Thank you for noticing the issues.  They have been fixed in the pull requests above.

> Yet, although the CMakeLists.txt file does not use it in the build target, it checks to make sure it is there when installing. 

The recommended way of using libh2o is to use it together with libuv.  This is because I believe that using libuv would be easier from the library users' point of view (as an example, consider a case in which you are writing an application using libh2o that connects to a database server.  You would need an asynchronous binding to the database server.  Evloop does not have (nor is unlikely to have) such kind of binding.  OTOH such binding exists for libuv, since it is popular).

Of course you are free to build and use your own libh2o with `-DH2O_USE_LIBUV=0`.

I might accept a PR that install two types of libh2o (one with `-DH2O_USE_LIBUV=1` and the other set to `0`), but I am not sure if it is the right thing to do, since as I expect that the majority would prefer the one using libuv, and since people looking for minor configurations could just build them by themselves (as a subproject or whatever).

**Comment by informer2000** [comment]
I'm still trying to use libuv with libh2o. The compilation error that I'm getting is not caused by libuv itself. I believe it is related to libh2o since an dummy main function in a file which includes only `uv.h` seems to be compiling with no errors. It is including `h2o.h` which causes the errors.

```
uv.h:648: error: declaration of C function 'int uv_tty_set_mode(uv_tty_t*, int)' conflicts with inline int uv_tty_set_mode(uv_tty_t* handle, int mode).

uv.h:641: error: previous declaration 'int uv_tty_set_mode(uv_tty_t*, uv_tty_mode_t mode)' here
UV_EXTERN int uv_tty_set_mode(uv_tty_t*, uv_tty_mode_t mode);
```

**Comment by vikmik** [comment]
A trick is to include uv.h before h2o.h in your code. Not ideal though

**Comment by kazuho** [comment]
FYI the compile error (when trying to use libuv and libh2o from C++ code in certain manner) has been resolved in https://github.com/libuv/libuv/pull/265.
