### ISSUE TITLE
H2O MRuby need performance improvement

### ISSUE THREAD

**Issue by proyb6** [h2o/h2o#1766]
H2O with MRuby appear to fare poorly at rank 109 which is quite far from H2O in C.

Chart:
https://www.techempower.com/benchmarks/#section=test&runid=61ff99e2-2392-4d7a-b6af-a5f081c5e004&hw=ph&test=json

https://github.com/TechEmpower/FrameworkBenchmarks/blob/70a2dac6639cf731dc7c5730333d2ce4116c39b5/frameworks/Ruby/h2o_mruby/h2o.conf

I wonder if any tips we can improve with it? Fiber? Probably MRuby-Rack-R3?
https://github.com/rail44/mruby-rack-r3

I feel plain text and json need to be fast.

**Comment by proyb6** [comment]
In addition if Crystal has been improving and close to Ruby, it's make a good option to integrate into H2O? It's seem an good enough for developers to write better code without rely on C in MRuby libraries and wider adoption.

@i110 CC

**Comment by i110** [comment]
I've not take any benchmarks on my own, but recently JSON serialization got faster by switching JSON library https://github.com/h2o/h2o/pull/1684
How about taking your benchmark with latest master?

**Comment by proyb6** [comment]
I forgot about that. if the test were using recently H2O and improve JSON, it improve slightly, I was a little disappointed.

250,529 (Round 15) to 271,771 (Unrelease)

**Comment by yannick** [comment]
even though the new json library is faster there would be much more gains that could be realized by switching the parser technique. but currently there is no readily available mruby lib that seemed ready. so this would need some work. 

crystal is a compiled language and you can use it to link against libh2o but its not suitable for dynamic h2o extensions.

**Comment by yannick** [comment]
in my opinion the json benchmark in the techempower benchmark is mostly useless since you can easily switch json implementation in h2o-mruby. 

sorry i was talking about plaintext result for h2o+mruby:
https://www.techempower.com/benchmarks/#section=test&runid=61ff99e2-2392-4d7a-b6af-a5f081c5e004&hw=ph&test=plaintext

so this precisely measures the mruby overhead compared to the (plain) h2o result.. 
the difference in the json benchmark is json parsing. 
imo getting better in this part of the benchmark is merely a vanity metric and has nothing to do with h2o. its just the library you choose. 
so speeding it up is a matter of writing a mruby gem that includes a faster parser and has little to do with h2o core.

**Comment by proyb6** [comment]
I see, will research further into this area

**Comment by proyb6** [comment]
@yannick Just have a surprise that MRuby-JSON is next to aspcore at 948K (that's 3.4x jump over old JSON libraries)

https://www.techempower.com/benchmarks/#section=test&runid=7dc8ea3a-6db5-41b8-a4d3-c18cfe72182b&hw=ph&test=json

**Comment by yannick** [comment]
@proyb6 cool!
