### ISSUE TITLE
[Question] How best to go about implementing X-Reproxy-URL handling

### ISSUE THREAD

**Issue by lestrrat** [h2o/h2o#187]
Context: I'm trying to write the reproxy handler/filter so that upstream apps can reply with a X-Reproxy-URL header.

At which point should this feature be hooked into? My concerns:

1. I want this to run AFTER a proxy request returned. Currently handler sequence stops once `on_req` returns 0, so that's probably not it
2. I want to re-use as much as I can from the proxy handler, because, well, a lot of the stuff is common (i.e., once x-reproxy-url is found, we need to initiate a proxy request, etc) -- I guess I should just dump my new handler/filter in proxy.c (this leads to more questions later, but I'll file that separately later)
3. Currently I'm guessing I need to hook into `h2o_setup_next_ostream`, but in that case, is there anyway I can tell h2o about possible proxy failures? The filter interface seems to only have `void` methods.
4. Or maybe this isn't the right place? Maybe there's a better hook for adding stuff after a proxy response has arrived?

Thanks in advance.

**Comment by kazuho** [comment]
@lestrrat Great! As the author of [mod_reproxy](https://github.com/kazuho/mod_reproxy) I would love to have the feature supported on H2O as well.

> 1\. I want this to run AFTER a proxy request returned. Currently handler sequence stops once on_req returns 0, so that's probably not it

Right.  Reproxying module should be implemented as a filter, not generator.

> 2\. I want to re-use as much as I can from the proxy handler, because, well, a lot of the stuff is common (i.e., once x-reproxy-url is found, we need to initiate a proxy request, etc) -- I guess I should just dump my new handler/filter in proxy.c (this leads to more questions later, but I'll file that separately later)

Reproxying module should not become part of the proxy module, since they serve different purposes, and since their would be differences in how they build the request / handle the response.  To name some of the behaviors that would be specific to reproxying module: a) reproxying module should recognize redirect responses and re-issue a request upon seeing them, b) reproxying module should send only _some_ of the request headers to the reproxied server, c) reproxying module should send only _some_ of the response headers sent by the reproxied server to the client.

Instead of implementing reproxy inside proxy.c, I would suggest moving code that should be shared out from proxy.c.

> 3\. Currently I'm guessing I need to hook into h2o_setup_next_ostream, but in that case, is there anyway I can tell h2o about possible proxy failures? The filter interface seems to only have void methods.

You are looking at the right function.  Reproxying module should be implemented as a filter, and filter should call `h2o_add_ostream` and `h2o_setup_next_ostream` to rewrite the output (as a output stream handler).

Regarding your question on how should the errors be handled, the point is that you would not need to notify errors to the generator (or ostreams running before the reproxying module).  What you should do is:

1. when the `on_setup_stream` callback of the reproxying filter is called and a `X-Reproxy-URL` header exists within the response, then
 * initiate a HTTP request to the designated URL
 * call `h2o_add_ostream` to register the output stream filter
2. when you receive a successful HTTP response (or fails), then
 * fill-in `req->res` with the response headers, and then call `h2o_setup_next_ostream`
3. when the `do_send` callback gets called
 * just ignore the content being passed in, as you do not need to send them in case of a reproxying module
 * call `h2o_ostream_send_next` immediately if you have any data that can be sent
 * or do nothing, and call `h2o_ostream_send_next` when additional data arrives from the reproxied server

In case the reproxying module fails to obtain data from the reproxied server, then it should update `req->res` with a 502 response within step 2.

**Comment by lestrrat** [comment]
@kazuho: Am I correct in that once we're in `on_setup_ostream` (i.e. after the `http1client` gives us something to work with) we can't rely on the `h2o_req_t *req` structure being available?

I've been trying to follow your recipe, and when I send the reproxy'ed new request to the new url, I'm trying to just pass in a copy of the original request to `http1client`'s request sequence... and failing miserably.
1) Am I going the wrong path?
2) If not, am I correct that I would need to clone the original request, or at least create a completely new request?

**Comment by kazuho** [comment]
@lestrrat 
> Am I correct in that once we're in on_setup_ostream (i.e. after the http1client gives us something to work with) we can't rely on the h2o_req_t *req structure being available?
> 
> I've been trying to follow your recipe, and when I send the reproxy'ed new request to the new url, I'm trying to just pass in a copy of the original request to http1client's request sequence... and failing miserably.

You can rely on `h2o_req_t*` and its memory pool.  They are _preserved until_ you call `h2o_ostream_send_next` with `is_final` flag set to true, or after the request is being cancelled (in which case the `stop` callback would be called if being set).

**Comment by kazuho** [comment]
closing the issue now that the feature has been merged to master.  Thank you for your contribution!
