### ISSUE TITLE
libh2o async database example

### ISSUE THREAD

**Issue by jobs-git** [h2o/h2o#1949]
How to add the database to the main event loop to take advantage of asynchronous programming in libh2o?

Say for example, a mysql database in a libh2o application. The program below is a `c-code` for mysql, but I doubt that just placing it in my libh2o application would automatically make it async

```c
 #include <mysql.h>
 #include <stdio.h>
 main() {
     MYSQL *conn;
     MYSQL_RES *res;
     MYSQL_ROW row;
     char *server = "localhost";
     char *user = "root";
     char *password = "PASSWORD"; /* set me first */
     char *database = "mysql";
     conn = mysql_init(NULL);
     /* Connect to database */
     if (!mysql_real_connect(conn, server,
         user, password, database, 0, NULL, 0)) {
        fprintf(stderr, "%s\n", mysql_error(conn));
        exit(1);
    }

    /* send SQL query */
    if (mysql_query(conn, "show tables")) {
        fprintf(stderr, "%s\n", mysql_error(conn));
        exit(1);
    }
    res = mysql_use_result(conn);

    /* output table name */
    printf("MySQL Tables in mysql database:\n");
    while ((row = mysql_fetch_row(res)) != NULL)
        printf("%s \n", row[0]);

    /* close connection */
    mysql_free_result(res);
    mysql_close(conn);
}
```

**Comment by volyrique** [comment]
`libh2o` can't make it possible to access a database asynchronously unless the latter provides the necessary API (and no, doing blocking operations in a separate thread and communicating with it via `h2o_multithread_receiver_t` doesn't count, but if it is acceptable to you, give it a try). In particular, it is not possible with MySQL because AFAIK there is no relevant C interface, though you might be able to make it work if you start with plain sockets and implement the protocol from scratch. As for other databases, I wrote an [implementation](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/C/h2o/src/database.c) for PostgreSQL.

**Comment by jobs-git** [comment]
a bit difficult for me to manage, but at least there was already an existing example. Thanks!
