### ISSUE TITLE
Async HTTP not working

### ISSUE THREAD

**Issue by jobs-git** [h2o/h2o#1986]
As the title suggest, it seems, that libh2o does not automatically do async http

**Comment by meritozh** [comment]
All network IO based on event loop. It should be async. Check `examples/libh2o/httpclient.c` first.

**Comment by jobs-git** [comment]
I used the techempower and added some code to `fortunes` and `database.c` (This is the fastest code sample I can look for h2o so I used it). I created a condition there that gets the static function sleep for 50s on 5th request. Now of course that 5th request will wait 50s, the 6th request coming from a different browser tab should of course go on as usual and dont care about the 5th request, and well unfortunately, it stalled like libh2o was waiting for the 5th request to finish before doing the 6th one. 

Could it be that the techempower h2o code was not async, however its just use the typical libh2o, so I am expecting it to be async as you mentioned.

Here is the code that I added to block the 5th request:

```c
int rad = 1; //this should be global so we could have a counter
some function(){
	if(rad==5){
		usleep(rad*10000000);
	}
rad++;
}
```

**Comment by meritozh** [comment]
_block_ does not mean _sync_, they are two concept:

- block: current task cannot be process until previous task finished.
- async: the callee notify caller, the result/effect. _callback_ is one async way.

For example, JS env is single thread which means it must process tasks one by one, block, but async/await feature let us write async code.

For your case, I don't which phase the blocking happen, before sending req, or before receiving res?

The `examples/libh2o/httpclient.c` is block async code because it only use one same thread.

**Comment by jobs-git** [comment]
Thank you for clarifying it, I though async would be the term since its usage in other projects while in fact they would mean non-blocking, my problem was instead due to blocking.
