### ISSUE TITLE
h2o: unable to build against OpenSSL with NPN disabled

### ISSUE THREAD

**Issue by James-TR** [h2o/h2o#2056]
I have been experiencing issues building h2o on OpenWRT where NPN has been disabled by default on the OpenSSL library they are distributing. It would be great if there was a way to dynamically detect what features are exposed and disable the code so it doesn't cause issues like this to crop up.

**Comment by omasanori** [comment]
Not dynamically (i.e. detect if it is available in `*.so` run-time), but we can check if NPN is supported build-time using `OPENSSL_NO_NEXTPROTONEG` defined in `openssl/opensslconf.h` if it is disabled. (at least with original OpenSSL; I am not sure about LibreSSL.)
As I prefer feature detection over version detection (assuming every default features in that version are available unconditionally) and I once [proposed to deprecate NPN completely](https://github.com/h2o/h2o/pull/1811), I love this proposal.

Since OpenSSL provides anti-feature detection macro scheme, we should write something like "enable if the version is newer than x.y.z and `OPENSSL_NO_ABC` is not defined" instead of "enable if `OPENSSL_ABC` is defined" ([an example](https://github.com/h2o/neverbleed/blob/d3d8d54f7526bc24e4c80f2d3511c9443fd078ab/neverbleed.c#L51-L52)). Thus we will get some more complex `#if`s, but the codebase will become more stable against future changes by OpenSSL/LibreSSL projects and distributions.

**Comment by James-TR** [comment]
I've opened https://github.com/h2o/h2o/pull/2195 to address this issue :)
