### ISSUE TITLE
PUSH_PROMISE and PROTOCOL_ERROR from client

### ISSUE THREAD

**Issue by brk0v** [h2o/h2o#218]
Hi, 

I'm trying to test http2 server pushes and got a strange error. 

My browser is FireFox Nightly 39.0a1 (2015-03-09). But it reproduces in 36.

My h2o config:

```
listen:
    port: 443
    ssl:
        certificate-file: ./server.crt
        key-file: ../server.key
hosts:
    "http2.local:8080":
        paths:
            /:
                proxy.reverse.url: "http://127.0.0.1:8080"
```
h2o version is 1.0.1.
I've patched code for enabling push in settings by default:

```c
const h2o_http2_settings_t H2O_HTTP2_SETTINGS_HOST = {
    4096,   /* header_table_size */
    1,      /* enable_push */
    100,    /* max_concurrent_streams */
    262144, /* initial_window_size */
    16384   /* max_frame_size */
};

static const h2o_iovec_t SETTINGS_HOST_BIN = {H2O_STRLIT("\x00\x00\x12"     /* frame size */
                                                         "\x04"             /* settings frame */
                                                         "\x00"             /* no flags */
                                                         "\x00\x00\x00\x00" /* stream id */
                                                         "\x00\x02"
                                                         "\x00\x00\x00\x01" /* enable_push = 0 */
                                                         "\x00\x03"
                                                         "\x00\x00\x00\x64" /* max_concurrent_streams = 100 */
                                                         "\x00\x04"
                                                         "\x00\x04\x00\x00" /* initial_window_size = 262144 */
                                                         )};
```

On 127.0.0.1 on the server side I have nginx with header for index.html `Link: </css.css>; rel=preload`. When I ask index.html page I got RST stream with PROTOCOL_ERROR. 

```
client ip: 192.168.32.1
server ip: 192.168.32.10
```

### tcpdump

*SETTINGS frame from server*

![](http://habrastorage.org/files/131/8e4/7b5/1318e47b548d426989b9aa9a3b796c56.png)

*PUSH stream*

![](http://habrastorage.org/files/0e0/1d8/3b7/0e01d83b730c450a9233c9263b381ff1.png)

*RST from client*

![](http://habrastorage.org/files/af6/bee/01a/af6bee01ac6248b289980c91539df8a5.png)

*And a question*: why does server send push promise frame and push response after main request? Is it valid behavior? RFC says:

> The server SHOULD send PUSH_PROMISE (Section 6.6) frames prior to sending any frames that reference the promised responses. This avoids a race where clients issue requests prior to receiving any PUSH_PROMISE frames.

> For example, if the server receives a request for a document containing embedded links to multiple image files, and the server chooses to push those additional images to the client, sending push promises before the DATA frames that contain the image links ensures that the client is able to see the promises before discovering embedded links. Similarly, if the server pushes responses referenced by the header block (for instance, in Link header fields), sending the push promises before sending the header block ensures that clients do not request them.

**Comment by kazuho** [comment]
@brk0v Thank you for noticing the issue.

Is it possible to serve the pushed files locally (by using `file.dir` handler of H2O)?  I believe that would be an workaround.

FYI, H2O is currently designed to:
- send all responses ASAP
- only send server push for successful responses (in other words, the server delays the emission of the `PUSH_PROMISE` frame until it knows the response headers of the request to be pushed)

Since H2O does not block until the upstream server sends a response, it is sending the main response prior to the pushed response.  If you could change the content of the pushed response to be served by the file handler the problem would likely disappear, since the handler builds the response synchronously.

To fix the issue, we would need to one of the following:

1. delay sending the main response until H2O collects all the response headers of the pushed responses
2. do not assert that a response of a pushed request is successful (by delaying the send timing of the `PUSH_PROMISE` frame)
3. limit the use of the feature for handlers that build response headers synchronously

2 seems like the best solution (1 has the drawback that it might cause slowdown in content delivery), but I have not yet made up mind.

**Comment by brk0v** [comment]
Thank you, for answer. 

From my point of view server should send PUSH_PROMISE frames ASAP for preventing races on the client side. And in case of  unsuccessful response from the backends – just reset this stream or do nothing (waiting for client timeout for pushes). 

Yeah, case with local files interesting, but not always enough.

**Comment by kazuho** [comment]
@brk0v Agreed that we should better send `PUSH_PROMISE` ASAP / reset the stream when upstream sends an error response.

note: unfortunately HTTP/2 forbid pushing non-cacheable streams, so in case the upstream server sends an error response (which is in most cases not cacheable) we would need to reset the stream without sending _why_ it failed (see also [RFC 7234](https://tools.ietf.org/html/rfc7234))

**Comment by kazuho** [comment]
@brk0v fixed in the PR above.  It would be great if you could check if it is working on your side.  Thank you in advance.
