### ISSUE TITLE
Some warnings about returning/comparing unsigned against -1

### ISSUE THREAD

**Issue by mingodad** [h2o/h2o#223]
On function "ssize_t h2o_server_starter_get_fds(int **_fds)" there is several "return -1" and also on main there is a comparison of the return value against "-1", probably the return type was "int" before and was changed without looking at all of it's usages.

I'm trying to compile h2o through c++ and found it.

Cheers !

**Comment by kazuho** [comment]
Thank you for noticing the issue.

The return type was not the problem (since `ssize_t` (not `size_t`) is a signed type), but in src/main.c it was assigned to `size_t` and then compared against `-1`.

Anyways I have fixed the problem in the commit above by changing the return type to `size_t` and using `SIZE_MAX` for indicating errors.

Please report back if you still see any problem.  Thank you for your help!
