### ISSUE TITLE
Question - Performance Benchmark Result

### ISSUE THREAD

**Issue by mohsenomidi** [h2o/h2o#2233]
Hi, 

I just found this URL ( [Web Framework Benchmarks](https://www.techempower.com/benchmarks/#section=data-r18&hw=ph&test=plaintext) ) to benchmark the different web framework and the results shows the H2O ranking as well, as i found in the project README file, that is very fast and also provides much quicker response, i am not expert in bench-marking and analyze the results, may it is wrong, just i want to know, is this benchmark valid ? or why the H2O rank is not very good in different sections. 

Regards.

**Comment by proyb6** [comment]
Not based on real-world benchmark, the question could be what do you intend to use H2O?

**Comment by proyb6** [comment]
Not based on real-world benchmark, the question could be what do you intend to use H2O and the requirements in your projects is going to have an impact in many areas or simply for normal websites and MRuby will be sufficient for most use case.

Big performance difference between VPS and dedicate server as well, the most accurate run your own benchmark starting with the routers https://github.com/the-benchmarker/web-frameworks

**Comment by mohsenomidi** [comment]
actually i want to use the **H2O as library** in my C++ project, but it is not well documented (**_it means there is no documentation_**) in this regard, and i am trying to find functionality, in this way, i faced with this benchmark ( [TechEmpower Framework Benchmarks GitHub Page ](https://github.com/TechEmpower/FrameworkBenchmarks)  ) but there is significant differences for TPS and processing,  specially in the **simple plain text** result  (runs on **Dell R440 Xeon Gold + 10 GbE**)

The benchmark Requirements summary says: 

> In this test, the framework responds with the simplest of responses: a "Hello, World" message rendered as plain text. The size of the response is kept small so that gigabit Ethernet is not the limiting factor for all implementations. HTTP pipelining is enabled and higher client-side concurrency levels are used for this test

the condition on hardware and resources are the same for all other libraries.

as i said this result should be evaluate by the experts, i am not a good person to check this, i am just a developer on particular part of business, not expert in HTTP protocol, just only familiar for using it as a library :)

**Comment by volyrique** [comment]
The key thing to realize is that the TechEmpower benchmarks are not **Web server** benchmarks, but **Web framework** ones. Even though their [definition of framework](https://www.techempower.com/benchmarks/#section=motivation) is quite loose (and includes cases such as `libh2o`, i.e. basic HTTP server libraries that they refer to as *platform*), the benchmarks cover much more than what is strictly the responsibility of a HTTP server. Out of the seven currently defined tests, only three are IMHO of a significant interest to Web server developers - JSON serialization, plaintext, and cached queries. The rest have database access as the bottleneck.

The [README file](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/C/h2o/README.md) of the test implementation based on `libh2o` documents the likely causes for performance issues. Since you are talking about the plaintext test in particular - keep in mind that it is the least realistic test. In particular, it uses **HTTP/1** pipelining extensively, and my impression is that efficient support for it (as opposed to HTTP/2 and later) is not really a priority in `libh2o` (@kazuho may confirm) - in fact, Web browsers [almost always](https://en.wikipedia.org/wiki/HTTP_pipelining#Implementation_in_web_browsers) disable it by default. The effect is that at least one system call is necessary per pipelined response, which as you can see doesn't lead to great results. Unfortunately, from my understanding of the code base improving this behaviour would require intrusive changes (and would increase complexity) and would potentially increase memory usage due to the additional response buffering.
