### ISSUE TITLE
startup delay

### ISSUE THREAD

**Issue by axelu** [h2o/h2o#2311]
after h2o is started, it takes minutes before it is ready to serve requests.
The error log reports the start of the worker instantly (1st line in below log excerpt), and then minutes later it adds the lines as shown below, and only then is it serving requests.  It is listening instantly after restart, meaning the ports are open, but it is not answering. It applies to both ports, http and https.  There are no other log entries related to this anywhere else on the system.  I assume it has to do with the OCSP stapling, but not sure.  Any help to get it to answer faster after a restart is appreciated, including help how to debug what it is actually doing respectively waiting for during that time.  Issue observed in 2.2.6 and 2.3.0_beta1.

> starting new worker 1109
[INFO] raised RLIMIT_NOFILE to 1073741816
h2o server (pid:1109) is ready to serve requests
fetch-ocsp-response (using OpenSSL 1.1.1d FIPS  10 Sep 2019)
fetch-ocsp-response (using OpenSSL 1.1.1d FIPS  10 Sep 2019)
sending OCSP request to http://ocsp.int-x3.letsencrypt.org
sending OCSP request to http://ocsp.int-x3.letsencrypt.org
/etc/letsencrypt/live/www.domain.com/fullchain.pem: good
	This Update: Apr 25 13:00:00 2020 GMT
	Next Update: May  2 13:00:00 2020 GMT
verifying the response signature
/etc/letsencrypt/live/www.domain.com/fullchain.pem: good
	This Update: Apr 25 13:00:00 2020 GMT
	Next Update: May  2 13:00:00 2020 GMT
verifying the response signature
verify OK (used: -VAfile /tmp/Hhf6gP1kzN/issuer.crt)
[OCSP Stapling] successfully updated the response for certificate file:/etc/letsencrypt/live/www.domain.com/fullchain.pem
verify OK (used: -VAfile /tmp/eV54DySy1h/issuer.crt)
[OCSP Stapling] successfully updated the response for certificate file:/etc/letsencrypt/live/www.domain.com/fullchain.pem

**Comment by paulpref** [comment]
Hello @axelu; since this is startup related, the environment in which you are running `h2o` matters a lot. If you could include details on the operating system you use and the how you start/launch `h2o` (manually, `systemd`, `launchd`, etc.) in the future, you will add to your chances of getting help.

That said, your startup log gives me the impression this is the same problem I have already encountered.

In my situation on Arch Linux (with multiple generations of the `linux-hardened` kernel, including the latest, `5.6.14.a`), using the system OpenSSL (`1.1.1g`), starting `h2o` with a `systemd` service unit, I noticed in the logs that the delay occurred between the `starting new worker` line and the `[INFO] raised RLIMIT_NOFILE to …` line.

I noticed that one of `h2o`’s subprocesses (it looks like the one handling the TLS private key) was running using all my CPU resources. Running `strace` on that process showed `h2o` _appeared_ to be attempting to _close every single handle_ starting from the soft limit. Here it is with a soft limit of 2<sup>10</sup>.

  	31940 prlimit64(0, RLIMIT_NOFILE, NULL, {rlim_cur=1024, rlim_max=512*1024}) = 0
  	31940 close(1023)                       = -1 EBADF (Bad file descriptor)
  	31940 close(1022)                       = -1 EBADF (Bad file descriptor)
  	31940 close(1021)                       = -1 EBADF (Bad file descriptor)
  	31940 close(1020)                       = -1 EBADF (Bad file descriptor)
  	…
  	31940 close(15)                         = -1 EBADF (Bad file descriptor)
  	31940 close(14)                         = -1 EBADF (Bad file descriptor)
  	31940 close(13)                         = -1 EBADF (Bad file descriptor)
  	31940 close(12)                         = -1 EBADF (Bad file descriptor)
  	31940 close(11)                         = -1 EBADF (Bad file descriptor)
  	31940 close(10)                         = -1 EBADF (Bad file descriptor)
  	31940 close(9)                          = -1 EBADF (Bad file descriptor)
  	31940 close(7)                          = -1 EBADF (Bad file descriptor)
  	31940 close(6)                          = 0
  	31940 close(5)                          = 0
  	31940 close(3)                          = 0

I had to tell `systemd` to reduce the [maximum number (the “hard limit”) of open file descriptors](https://www.freedesktop.org/software/systemd/man/systemd.exec.html) being given to `h2o`. Under the `[Service]` section of the unit file, I added/modified the `LimitNOFILE` setting to 2<sup>19</sup> (524288), which seems to be the default—but depending on your traffic, you may need more or be fine with less. I have absolutely no data to back up this choice. On my tiny server, I’ve been using 2<sup>21</sup> (2097152) without any trouble.

    [Service]
    LimitNOFILE=524288

This is considerably less than the roughly 2<sup>30</sup> (1073741824) you notice your log says is being used.

The lower the limit, the fewer tests `h2o` (or a system call it is making) does, the quicker it starts.


For reference, I’m using the `systemd` service unit that comes from the [`h2o` package in Arch Linux’s AUR](https://aur.archlinux.org/packages/h2o/).

    [Unit]
    Description=H2O - the optimized HTTP/1, HTTP/2 server
    After=network-online.target nss-lookup.target remote-fs.target

    [Service]
    Type=simple
    PIDFile=/run/h2o.pid
    ExecStart=/usr/bin/h2o --mode master --conf /etc/h2o.conf
    ExecReload=/usr/bin/kill -HUP $MAINPID
    ExecStop=/usr/bin/kill -TERM $MAINPID
    SyslogLevel=notice
    PrivateTmp=true
    #LimitNOFILE=infinity
    LimitNOFILE=2097152

    [Install]
    WantedBy=multi-user.target

**Comment by axelu** [comment]
@paulpref Thank you for sharing.  Issue for me was on Fedora 31, h2o started via systemd with `LimitNOFILE=infinity` in the corresponding service file.  That is in fact the issue. Thank you again.
