### ISSUE TITLE
OCSP Stapling errors on Mozilla Firefox

### ISSUE THREAD

**Issue by CarloMartini** [h2o/h2o#2478]
Hello,
The company I work for has an h2o dockerized istance (front-end for Apache) in a few different servers, and all of them - once in a while - have the problem of OCSP errors on Firefox clients, for some websites.

We solve "manually", that is by killing / respawing the running instances of h2o... But of course we need a permanent fix. 

Our cipher list is already in line with the one suggested by Mozilla (https://ssl-config.mozilla.org/). What else can we do? Would tinkering with ocsp-update-interval, ocsp-max-failures or num-ocsp-updaters be a good idea?

Thank you!

**Comment by kazuho** [comment]
I think the problem here is that the certificate is being replaced on disk, but h2o not being notified about the change.

H2O reads the certificate from disk when it is launched or when it is sent SIGHUP (assuming that it is run either in daemon mode or in master mode). However, the OCSP stapling information is periodically fetched based on the certificate that is on disk.

Therefore, if the certificate gets replaced on disk while H2O is not notified of the fact, there would be mismatch between the certificate and the OCSP information that would be sent.

The fix would be to send SIGHUP to H2O whenever you update the certificate on disk.

**Comment by CarloMartini** [comment]
Thank you @kazuho 
That actually solved it.
