### ISSUE TITLE
h2o almost perfect h2spec tests 65/66

### ISSUE THREAD

**Issue by centminmod** [h2o/h2o#268]
updated to latest master h2o and almost perfect :)

test timeout, is that a config issue in my h2o.conf or h2o itself ?

    /go/src/github.com/summerwind/h2spec/h2spec -h h2ohttp2.centminmod.com -p 8081 -t
    66 tests, 65 passed, 0 skipped, 1 failed
    
    ===============================================================================
    Failed tests
    ===============================================================================
    
      6.10. CONTINUATION
        × Sends multiple CONTINUATION frames
          - The endpoint must accept the frames.
            Expected: HEADERS frame
              Actual: Test timeout

**Comment by kazuho** [comment]
@centminmod Thank you for noticing the problem.

This was a timing-related issue in which the server in some cases missed to read the last TLS record being sent from the peer if it is greater than 4,096 bytes.

**Comment by centminmod** [comment]
@kazuho perfect 66/66 :)

    /go/src/github.com/summerwind/h2spec/h2spec -h h2ohttp2.centminmod.com -p 8081 -t

    66 tests, 66 passed, 0 skipped, 0 failed
    All tests passed

**Comment by devlearner** [comment]
Hi, thanks centminmod for the discovery and kazuho for the fix :)

It actually inspires me to repeat the test for myself :)
I pulled the latest master, and happen to notice that it's occassionally failing at 5.1.2

```
===============================================================================
Failed tests
===============================================================================

  5.1. Stream States
    5.1.2. Stream Concurrency
      × Sends HEADERS frames that causes their advertised concurrent stream limit to be exceeded
        - The endpoint MUST treat this as a stream error (Section 5.4.2) of type PROTOCOL_ERROR or REFUSED_STREAM
          Expected: GOAWAY frame (ErrorCode: PROTOCOL_ERROR)
                    RST_STREAM frame (ErrorCode: PROTOCOL_ERROR)
                    GOAWAY frame (ErrorCode: REFUSED_STREAM)
                    RST_STREAM frame (ErrorCode: REFUSED_STREAM)
                    Connection close
            Actual: Error: WSARecv tcp: An existing connection was forcibly closed by the remote host.
```
(I was using h2spec v0.0.8; I didn't have go installed, got lazy and grabbed a Windows binaries; the error message basically means a disconnect / connection close)

Interestingly, the test seems to fail intermittently. I repeated the specific test with `-s 5.1.2`:

```
$ h2spec -h [host] -p [port] -o 60 -s 5.1.2 (-t) [for ssl]

    h2o        h2o (ssl)

 1-16: FAIL   1- 9: FAIL
   17: PASS     10: PASS
 1- 6: FAIL   1- 8: FAIL
    7: PASS      9: PASS
    1: FAIL   1-60: FAIL
    2: PASS     61: PASS
 1- 3: FAIL   1- 3: FAIL
    4: PASS      4: PASS
    1: FAIL   1- 4: FAIL
    2: PASS      5: PASS
 1- 8: FAIL   1- 3: FAIL
    9: PASS      4: PASS
    1: PASS   1-12: FAIL
    1: FAIL     13: PASS
    2: PASS
 1- 7: FAIL
    8: PASS   * Counter begins at 1
    1: PASS     On each PASS, next counter
 1-28: FAIL                   resets to 1
   29: PASS
    1: PASS   # As a control, I also tested 
 1- 8: FAIL     nghttpx, which consistently
    9: PASS     PASSes ...
 1-20: FAIL
   21: PASS     nghttpx  1-100: PASS
 1- 8: FAIL                 
    9: PASS     ... this specific test
 1- 4: FAIL     (thou nghttpx fails some
    5: PASS      other sub-tests)
 1- 7: FAIL
    8: PASS
```

it doesn't fail all the time (it sometimes pass the test) any ideas about this?

**Comment by kazuho** [comment]
@devlearner Thank you for reporting the issue!

It was mostly an issue within h2spec (which I have created a fix shown above).  And the fix revealed a bug in H2O.

**Comment by devlearner** [comment]
Thanks @kazuho for the commit!

I pulled the latest master; and found out that it wasn't really h2o-specific (sorry for the noise :) )

Turns out that this seems to relate to how messages are chunked when sent from h2spec
I've dumped some interesting logs here:
https://www.googledrive.com/host/0BxAqXY_rV9MMVS1ncFVSaUdDeWM/h2spec-5.1.2.htm
[~~canvas overflow warning:~~ try to view this with the window maximized; sorry for the clustering ;) ]

Interestingly when chained to socat (for the dumps) between h2spec and h2o, the test mostly passes.
Glad to know that, in fact, h2o actually passes the test (does the right thing)
maybe it just relates to a timing issue how messages are processed 
(basically which means it's just a matter of representation)  :)

p.s. Sorry that I haven't tested the PR for h2spec yet (maybe it addresses the issue); since I'm not that familiar with the specs, maybe I'll leave that to the more intelligent ;)
from the logs that I linked above, it does seem to show that error frames are received from the server (h2o or nghttpd) when the test frames are sent in one 'chunk'... hope the logs would be useful  :)
