### ISSUE TITLE
What does "unable to get issuer certificate" mean?

### ISSUE THREAD

**Issue by LoganDark** [h2o/h2o#3010]
I'm getting a 502 error from h2o that says "unable to get issuer certificate". I don't know what I should do to solve it. I can't find any error index or anything that tells me what the problem is.

- There is nothing in the h2o logs (`sudo journalctl --unit=h2o.service -n 20`)
- `H2O_ROOT=/usr`
- `/usr/share/h2o/ca-bundle.crt` is present & up-to-date
- The backend nginx server is configured with a valid SSL certificate

Here is my `h2o.conf`:

```
#server-name: "h2o (Debian)"
send-server-name: OFF
user: www-data
access-log: "|rotatelogs -l -f -L /var/log/h2o/access.log -p /usr/share/h2o/compress_logs /var/log/h2o/access.log.%Y-%m-%d 86400"
error-log: "|rotatelogs -l -f -L /var/log/h2o/error.log -p /usr/share/h2o/compress_logs /var/log/h2o/error.log.%Y-%m-%d 86400"
pid-file: /run/h2o.pid

proxy.emit-x-forwarded-headers: ON
proxy.emit-via-header: OFF
proxy.emit-missing-date-header: OFF

hosts:
  default:
    listen:
      type: quic
      port: 443
      ssl:
        certificate-file: [REDACTED]
        key-file: [REDACTED]
    paths:
      "/":
        proxy.reverse.url: https://127.0.0.1:443/
        proxy.preserve-host: ON
        proxy.tunnel: ON
        proxy.header.unset: "X-Forwarded-For"
        proxy.header.unset: "X-Forwarded-For-Proto"
```

h2o version:

```
h2o version 2.3.0-DEV@fe5060646
OpenSSL: OpenSSL 1.1.1f  31 Mar 2020
mruby: YES
fusion: YES
```

**Comment by kazuho** [comment]
It's an error from TLS indicating that h2o failed to establish a secure connection against https://127.0.0.1:443/ (the URL designated by `proxy.reverse.url`), because the TLS server certificate provided from that URL could not be authenticated.

I can think of three ways moving forward:
* Switch to `http`. You might not need to use HTTPS when connecting to a server running on the same host.
* Make sure that OpenSSL installed on your server can authenticate the server certificate provided by `127.0.0.1:443`.
* Disable peer verification (https://h2o.examp1e.net/configure/proxy_directives.html#proxy.ssl.verify-peer).

**Comment by LoganDark** [comment]
> the TLS server certificate provided from that URL could not be authenticated

Ah, that's probably because the server there is providing a certificate for my domain, not for the IP address itself, right?

Turning off peer verification worked, thanks!
