### ISSUE TITLE
Do more releases, or take down your website

### ISSUE THREAD

**Issue by mattparlane** [h2o/h2o#3136]
If you want to have an internal-only project, that is your right and I have no problem with that. But you should not have a website and pretend to be a viable open source project, and not release anything for over three years.

Either be more active with the community and do more releases, or change this project to internal-only and take down your website.

**Comment by utrenkner** [comment]
While I, too, would like to see another official release, I must say that I am quite happy with the development here. I use a fairly recent snapshot on several production servers (thanks to @dch for the [www/h2o-devel port](https://www.freshports.org/www/h2o-devel/) in FreeBSD).

But just because no releases have been tagged as such by the developers does not make their huge contribution irrelevant - quite the contrary. There have been thousands of commits in the last years - all public and released under the MIT license, you can even follow their discussions here in the issues and PRs. 

I am super thankful to them and to Fastly for continuing H2O as an open source project. I would not know how to rebuild our infrastructure on something else. And I still frequently consult the website for the new configurations.
