### ISSUE TITLE
http2 unsigned number encoding/decoding has endianness issues

### ISSUE THREAD

**Issue by reem** [h2o/h2o#343]
This set of decoding functions defined in `http2_internals.h`:

```c
static uint16_t h2o_http2_decode16u(const uint8_t *src);
static uint32_t h2o_http2_decode24u(const uint8_t *src);
static uint32_t h2o_http2_decode32u(const uint8_t *src);
static uint8_t *h2o_http2_encode24u(uint8_t *dst, uint32_t value);
static uint8_t *h2o_http2_encode32u(uint8_t *dst, uint32_t value);
```

Assume that the network byte order is big endian and that the host architecture is little endian. This is often the case, but not always.

**Comment by kazuho** [comment]
Thank you for reporting the issue.

I think they are implemented correctly; the functions always read / write the most significant bits from the lowest address regardless of the endianness.  In other words, the chunked accessed using `uint8_t *` are always big endian.

But it has been years since I stopped using a big-endian machine, I cannot test the code.  Pull-request is welcome under the premise that they are implemented wrong.

**Comment by reem** [comment]
Thought about it some more and I think you are right - the functions will work on both a little endian and big endian machine, they could just be implemented *slightly* more efficiently as a "noop" on a big endian machine.
