### ISSUE TITLE
Feature request: PROXY protocol

### ISSUE THREAD

**Issue by Roze** [h2o/h2o#350]
Any chance of the Proxy protocol implementation ( http://www.haproxy.org/download/1.6/doc/proxy-protocol.txt ).

**Comment by kazuho** [comment]
Thank you for raising the topic.  Sounds interesting.

My understanding is that the use of `x-forwarded-for` header is preferred for proxying HTTP requests (and is supported by H2O), since by using the header it is possible for the reverse proxy to multiplex requests from many clients (using different addresses) to a single upstream server (note: the topic is also covered in the _Background_ section of the provided link).

Or are you looking for a proxy that transfers TCP connections?  H2O does not provide such feature (yet).

**Comment by Roze** [comment]
X-Forwardedfor headers become a bit cumbersome if there is a chain (of proxies) - for example in my case there would be h2o -> haproxy -> nginx so for each you would need to configure what are the trusted sources etc.
Obviously it can be done but seing how some other applications (like nginx, haproxy, stud) have implemented it, was thinking of it as a usefull/interesting addition.

**Comment by kazuho** [comment]
> Obviously it can be done but seing how some other applications (like nginx, haproxy, stud) have implemented it, was thinking of it as a usefull/interesting addition.

My understanding is that nginx does not prepend the `PROXY TCP4 ...` line when sending HTTP requests to upstream servers.

OTOH it does recognize the `PROXY ` lines of incoming connections.  Do you want H2O to that?  Sounds logical if that is the case.

**Comment by felixbuenemann** [comment]
This would indeed be great for serving http/2 via ELB or other tcp mode balancer like haproxy with PROXY protocol support.

**Comment by Roze** [comment]
> OTOH it does recognize the  PROXY  lines of incoming connections. Do you want H2O to that? Sounds logical if that is the case (for example in case if you want to place H2O behind EC2's ELB).

Indeed nginx doesn't officially support proxy protocol for upstreams (though a patchset exists https://github.com/yaoweibin/nginx_tcp_proxy_module/pull/110 ).

In general the best option (in my case) if h2o would support it both ways - as incoming and also being able to pass it to backends, but even either one option would simplify a lot of setups.

**Comment by kazuho** [comment]
@Roze @felixbuenemann FYI the feature has been added in the PR above.

**Comment by felixbuenemann** [comment]
@kazuho Thanks!

**Comment by Roze** [comment]
@kazuho Great will test it out. Thx!
