### ISSUE TITLE
How can I send as server a whole file to the client?

### ISSUE THREAD

**Issue by Thalak** [h2o/h2o#466]
Hi,
after a request by a client with a incorrect URL I want to map the url-query to my startpage. 
After such a request my server should sent a whole file like the  'index.html' to the client.

I try: 

        const char *path     = "/home/user/test/";
        const char *filename = "index.html";
        h2o_iovec_t mime_type;
        mime_type = h2o_strdup(&req->pool, "text/html", SIZE_MAX);

        req->res.reason = "OK";
        req->res.status = 200;
        h2o_add_header(&req->pool, &req->res.headers, H2O_TOKEN_CONTENT_TYPE, H2O_STRLIT("text/html"));
        h2o_start_response(req, &generator);
        h2o_file_send(req, 0, filename, path, mime_type, 0);

After the h2o_file_send() the client is still waiting for response. 

with use of:

      h2o_file_send(req, req->res.status, req->res.reason, pathAndFilename, mime_type, 0);

it's also not working. I think my parameters are still wrong. Can you help me please?

Regards,
Thalak

**Comment by kazuho** [comment]
> `h2o_start_response(req, &generator);`

It is most likely due to this line.  When called, the function emits the response headers (including `content-length`) to the protocol layer, and therefore should only be called by somebody who actually builds the response after all the headers are being set up.

In you case, the function responsible for building the response is `h2o_file_send` (the function also adjust the status line (e.g. `200 OK` and sets the `content-type`, `content-length` headers).  You are allowed to inject headers before calling `h2o_file_send`, but you should not call `h2o_start_response` by yourself.

**Comment by Thalak** [comment]
Hi,
with:

        const char* path = "/home/user/test/index.html";
        h2o_iovec_t mime_type;
        mime_type = h2o_strdup(&req->pool, "text/html", SIZE_MAX);
        req->res.reason = "OK";
        req->res.status = 200;
        h2o_file_send(req, req->res.status, req->res.reason, path , mime_type, 0);

it seems to work fine.

Thank you.    :)
