### ISSUE TITLE
Old log compression support request

### ISSUE THREAD

**Issue by zlm2012** [h2o/h2o#529]
Since a misconfiguration on my server, the access log and error log of h2o were flooded... That reminds me that the old logs could be compressed into a separated file like `syslog` in Debian. If not, after a long-term running, the logs would be very huge...

**Comment by kazuho** [comment]
My understanding is that traditionally such requirements have been handled by administration tools external to daemons.

One of such tools is logrotate, which is capable of sending signals to daemons periodically and then compressing the older logs.  I assume it is available in most Linux distributions.

The other is the [rotatelogs](http://httpd.apache.org/docs/2.4/programs/rotatelogs.html) command developed by Apache.  The command accepts the logs via pipe and writes to the appropriate file.  My understanding is that this command is also available in most Linux distributions.  In case of rotatelogs, you should setup cron (or something similar) to compress the older logs.

You can use either way in case of H2O.

FWIW, my preference goes to rotatelogs, since it requires _less_ coordination between the processes (which means that there would theoretically be less issues) when compared to logrotate.

**Comment by zlm2012** [comment]
Well... I should have read the rotatelogs usage in the wiki... Close this issue now. Thanks.

**Comment by kazuho** [comment]
:+1:
