### ISSUE TITLE
Why _pending and _statechanged of evloop are are implemented differently?

### ISSUE THREAD

**Issue by cwyang** [h2o/h2o#656]
Hi. 

Would you tell me why `_pending` and `_statechaged` of evloop are are implemented differently?

https://github.com/h2o/h2o/blob/master/include/h2o/socket/evloop.h 

This is libh2o's current implementation:
```
typedef struct st_h2o_evloop_t {
    struct st_h2o_evloop_socket_t *_pending;
    struct {
        struct st_h2o_evloop_socket_t *head;
        struct st_h2o_evloop_socket_t **tail_ref;
    } _statechanged; 
   ...
} h2o_evloop_t;
```
Why didn't you do like followings:
```
    struct st_h2o_evloop_socket_t *_pending;
    struct st_h2o_evloop_socket_t *_statechanged;
```

The difference is that while `_pending` adds new socket to head,`_statechanged` adds new socket to tail.
`_statechanged` sockets are used for event watching (epoll) and event watchers like epoll do not care about the order of regsitering event (`epoll_ctl()`)
I'll be happy to know why h2o should maintain `_statechanged` as FIFO queue.

Thank you.

**Comment by kazuho** [comment]
> I'll be happy to know why h2o should maintain _statechanged as FIFO queue.

Actually, the two were FIFO in the very early days.

`_pending` was changed to LIFO for performance reasons (since calling the completion callback right after completing each `write` has a big benefit in terms of memory footprint), but `_statechanged` has been left as it is until now.

Neither do I see any reason that prevents us from changing `_statechanged` to LIFO too.

**Comment by cwyang** [comment]
Thank you for Kind explanation. :-)
