### ISSUE TITLE
Setting of environmnt variables possible?

### ISSUE THREAD

**Issue by utrenkner** [h2o/h2o#694]
Hi,

there are quite a few web application that change their behaviour based on environment variables, which are configured via Apache's vhost definitions or via .htaccess.

The most common occurrence for these allows to define whether the particular vhost/directory works in "production" or "development" mode. Warning messages and other debugging related options can thus be switched off/on.

Can this be done with h2o/mruby, too?

**Comment by kazuho** [comment]
Under the assumption that you are using the `fastcgi.spawn` directive to start your web application (otherwise the web application will not be invoked by H2O), you can set the parameter by specifying the environment variable within the shell expression that invokes the FastCGI daemon.

In case of the example the following example found in https://h2o.examp1e.net/configure/fastcgi_directives.html#fastcgi.spawn, `PSGI_FCGI_CHILDREN` is an environment variable that is set to `10`.  You can repeat `name=value` strings to set environment variable before invoking the daemon process via `exec`; please refer to the documentation of `sh` (or `bash` in case of Linux) for details.

```
file.custom-handler:
    extension:     .php
    fastcgi.spawn: "PHP_FCGI_CHILDREN=10 exec /usr/local/bin/php-cgi"
```

**Comment by utrenkner** [comment]
Sorry, I realise that I did not make my question clear enough. I meant: I just have some PHP code running under one domain and this code should be able to access a certain environment variable (PHP-FPM is connected via UNIX socket and I do not start any fcgi-children).

For Apache one can define this in the vhost section or in an .htaccess, e.g.:
```
SetEnv APPLICATION_ENV development
```

**Comment by kazuho** [comment]
Thank you for the clarification.  I now understand that the feature is missing and we would need to implement it.

**Comment by utrenkner** [comment]
FYI, in nginx this is passed on via fastcgi_param, e.g.

```
location / {
   fastcgi_param   APPLICATION_ENV  production; #APPLICATION_ENV = production
   (...)
}
```

**Comment by kazuho** [comment]
With the merger of #868, you can now use `setenv` and `unsetenv` directives to set / unset environment variables.

The directives can be used at any of the global, host, path, and extension level; they are applied in the order from outer scope to inner.
