### ISSUE TITLE
Read/write errors on server

### ISSUE THREAD

**Issue by karantin2020** [h2o/h2o#721]
Hello. I tested h2o 1.7.0-beta4 lib with wrk. That are the results:
```sh
$ wrk -d300s -c10000 -t4 --timeout 20s http://localhost:7890/chunked-test/
Running 5m test @ http://localhost:7890/chunked-test/
  4 threads and 10000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   157.90ms   80.07ms   1.16s    84.33%
    Req/Sec    10.31k     5.94k   35.12k    64.99%
  11319895 requests in 5.00m, 1.91GB read
  Socket errors: connect 0, read 5, write 6882, timeout 0
Requests/sec:  37720.41
Transfer/sec:      6.51MB
```

Tested with client and server on one local host. I tested different number of connections.
Results are: more connections and more time of test mean more errors.
Even few connections get errors:
```sh
$ wrk -d300s -c1000 -t4 --timeout 20s http://localhost:7890/chunked-test/
Running 5m test @ http://localhost:7890/chunked-test/
  4 threads and 1000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    23.33ms    2.49ms 248.43ms   91.41%
    Req/Sec    10.73k     0.88k   14.87k    78.05%
  12817493 requests in 5.00m, 2.16GB read
  Socket errors: connect 0, read 3, write 0, timeout 0
Requests/sec:  42715.57
Transfer/sec:      7.37MB
```

Is there any way to correct it?
Thanks

**Comment by kazuho** [comment]
> Results are: more connections and more time of test mean more errors.

It is likely that H2O is out of file descriptors.

Q1. What is the number of `RLIMIT_NOFILE`?

The number is the cap. for maximum number of file descriptors that can be used within a single process.  If you see in the error log of H2O (or in standard error output) during the start up a line starting from `[INFO] raised RLIMIT_NOFILE to `, then it would show you the number of `RLIMIT_NOFILE` raised to the maximum. If otherwise, the limit will be equal to the value obtained by running `ulimit -n`.

Q2. If Q1 does not address your issue, please describe what your are trying to test.  I assume you are trying to test certain feature (or a combination of features) of H2O considering the fact that your path says `/chunked-test/`.

**Comment by kazuho** [comment]
Sorry, I had not noticed that you are reporting an issue for libh2o.  Assuming that you are running `examples/libh2o/simple.c`,
* I cannot reproduce the issue if `-c` is set to below the value of `RLIMIT_NOFILE` (plus some delta for standard i/o and the listening socket)
* if I set `-c` above `RLIMIT_NOFILE` I see an error like
```
$ wrk -d30s -c10000 --timeout 20s http://localhost:7890/chunked-test/
Running 30s test @ http://localhost:7890/chunked-test/
  2 threads and 10000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    29.93ms   20.98ms 327.48ms   91.15%
    Req/Sec    19.00k     7.96k   48.18k    89.09%
  559129 requests in 30.59s, 96.51MB read
  Socket errors: connect 7957, read 432554, write 0, timeout 116398
Requests/sec:  18278.28
Transfer/sec:      3.16MB
```

This looks like different from what you are seeing; if your issue is not related to `RLIMIT_NOFILE`, you may also want to check if the backlog size used by the example is sufficient; [it is hard-coded to 128](https://github.com/h2o/h2o/blob/v1.7.0-beta4/examples/libh2o/simple.c#L131) which might be too small for a benchmark client that tries to establish many connections at once.

**Comment by karantin2020** [comment]
Hello. My `ulimit -n` 65536.
Changing backlog value helped.
From docs there is:
```markdown
`backlog` indicates the number of connections the kernel might queue
```
Could you help what is the limit of backlog?
