### ISSUE TITLE
Update LibreSSL to 2.2.6

### ISSUE THREAD

**Issue by utrenkner** [h2o/h2o#727]
Maybe you could update the bundled LibreSSL to 2.2.6 before the 1.7 release? The new version was released yesterday, with the following notice:

`LibreSSL 2.2.6 and 2.1.10 contain a single change to deprecate use of the SSL_OP_SINGLE_DH_USE flag. It is now enabled unconditionally.`

This is in reaction to the (potential) problem explained here:
https://www.openssl.org/news/secadv/20160128.txt

Thanks!

**Comment by kazuho** [comment]
Thank you for raising the issue.  Will do it.

FWIW, by reading the following lines in the advisory I believe is that H2O using prior versions of OpenSSL / LibreSSL is not vulnerable to this issue (i.e. CVE-2016-0701), since we set `SSL_OP_SINGLE_DH_USE` in case the server is configured to use DH parameters that are not "safe".

> Where an application is using DH configured with parameters based on primes that are not "safe" then an attacker could use this fact to find a peer's private DH exponent. This attack requires that the attacker complete multiple handshakes in which the peer uses the same private DH exponent.
> (snip)
> OpenSSL provides the option SSL_OP_SINGLE_DH_USE for ephemeral DH (DHE) in TLS. It is not on by default. If the option is not set then the server reuses the same private DH exponent for the life of the server process and would be vulnerable to this attack.
https://www.openssl.org/news/secadv/20160128.txt

**Comment by utrenkner** [comment]
Great to hear that you ensured safe configuration even before this patch. Many thanks!

**Comment by kazuho** [comment]
Actually, I
