### ISSUE TITLE
configuration of unix domain socket

### ISSUE THREAD

**Issue by tomquas** [h2o/h2o#729]
h2o 1.6.3 on ubuntu and osx

i have h2o open a unix domain socket; a few things i observed:

* socket file creation does not seem to pay attention to a user configuration setting. in my case, i defined ```user: www-data```, the socket file is owned by root though. expected: www-data should be the owner

* a concept of setting socket file permissions, similar to redis' ```unixsocketperm```, seems to be missing entirely yet

**Comment by kazuho** [comment]
Thank you for bringing the issue up.

Though I am not against providing a directive to change the permission of a Unix socket file, I would like to point out that you should not rely on the permissions of a Unix socket file.  Instead, you should control the accessibility of the socket by creating the socket file within a directory that has appropriate permissions set.

Quoting from `man 7 unix` of Linux,
~~~
       In the Linux implementation, sockets which are visible in the filesystem honor the permissions of the  directory  they  are  in.
       Their  owner, group and their permissions can be changed.  Creation of a new socket will fail if the process does not have write
       and search (execute) permission on the directory the socket is created in.  Connecting to the socket object requires  read/write
       permission.   This  behavior  differs  from many BSD-derived systems which ignore permissions for UNIX domain sockets.  Portable
       programs should not rely on this feature for security.
~~~

And if you control the accessibility of a Unix socket using the permissions of a directory that contains the socket, I believe that the owner of the socket file will not be an issue.

**Comment by tomquas** [comment]
thank you @kazuho. i changed my boot script according to your information: it now creates a parent directory for the socket file which has permissions 700 and ownership ```www-data:www-data```.

the issue remains: the socket file created by h2o belongs to ```root```.

**Comment by kazuho** [comment]
> the issue remains: the socket file created by h2o belongs to root.

At the moment, H2O creates the socket file before dropping the root privilege.  So if you start the server as root, then the socket file will be created by root.

Is the behavior causing any issue?  

For a directory without sticky bit set, the owner of the socket file does not cause any difference, since users with the ability to modify the directory can remove any file within that directory.

For a directory with sticky bit set (i.e. `/tmp`), I believe it is actually better to have it owned by root (if H2O was started by root), since it would prevent other processes spawned by H2O (e.g. CGI process) from removing the socket file.

**Comment by tomquas** [comment]
i don't think it's actually a question of sticky bits; let's go one step back:

i have a number of processes running as ```www-data``` which need to communicate via http. i want to add an h2o process to provide another service. h2o should offer communication via unix socket for performance reasons.

that said, with today's implementation, h2o creates a socket file with the following permissions:

```srwxr-xr-x 1 root root 0 Feb  2 09:40 h2o.sock=```

communication is broken, because processes other than ones running as ```root``` are not allowed to write to the socket.

As opposed to h2o, this is how docker solves it:

```srw-rw----  1 root       docker        0 Jan 31 13:19 docker.sock=```

imho, a quick fix could be to change group ownership and permissions for the socket file, taking into account the ```user: ...``` configuration setting.

which brings me back to my point about redis and ```unixsocketperm```. being explicit in config files eliminates dependencies to more-or-less fancy startup scripts and lets me track down issues faster. another good example of being explicit on permissions is [haproxy](https://cbonte.github.io/haproxy-dconv/configuration-1.5.html#9.2 haproxy).

**Comment by kazuho** [comment]
@tomquas Thank you for elaborating.

I agree that the socket file not having write bit for group and others being set is an issue, since many systems (e.g. Linux) refers to the bit.

We should provide a way for a user to configure the permissions.  And if are provide such feature, then it would be natural for a user to expect a way to configure the file owner as well...

**Comment by kazuho** [comment]
@tomquas `owner` and `permission` attributes have been implemented in the PR above, merged to master.  An usage example is shown in https://github.com/h2o/h2o/blob/c6ec97fde2892ba8ab033bb65a19e3ff2a1c6c71/srcdoc/configure/base_directives.mt#L226-L230.

Please let me know if you still see issues.  Thank you in advance.

**Comment by tomquas** [comment]
awesome. thanks a lot.
