### ISSUE TITLE
Question regarding "return" in mruby handler

### ISSUE THREAD

**Issue by utrenkner** [h2o/h2o#755]
@kazuho In a [recent issue thread](https://github.com/h2o/h2o/issues/747#issuecomment-181559530) you explained that `return` should not be used in a `do...end` block.

But in some of the [mruby examples](https://h2o.examp1e.net/configure/mruby.html) this construct seems to be used, namely the examples on "Access Control" and "Delegating the Request".

As I am using the example code for the delegation of a request myself, I would be interested to understand why this is acceptable in these circumstances but not in the 301 redirect suggested in #747 . Could you explain the difference?

**Comment by kazuho** [comment]
@utrenkner Sure!

First, as required by the Rack interface specification, a mruby handler must return a three-element tuple, containing the status code, response headers, and the body.

That said, the question comes to how you can write such a handler.

When `Proc.new` is used to define a Rack handler, then its last expression being evaluated becomes the return value.  You should never execute a `return` statement within a Rack handler defined with `Proc.new`, since a `return` statement within `Proc.new` instructs ruby to return from a method that _called_ `Proc.new`.

When `lambda` or a method is used to define a Rack handler, then the `return` statement of the lambda (or the method) becomes the return value, or in case the lambda (or the method) exitted without executing a `return` statement, then the last expression being evaluated becomes the return value.

**Comment by utrenkner** [comment]
@kazuho Thank you so much. This is really helpful!
