### ISSUE TITLE
file.send-compress not yet active in 2.0.0-DEV

### ISSUE THREAD

**Issue by minami-o** [h2o/h2o#844]
Hi there,
First off, thanks a lot for this great piece of software you have built!
I happened to notice [in the documentation](https://h2o.examp1e.net/configure/file_directives.html#send-compress) that a new option "file.send-compress" is meant to obsolete "file.send-gzip" in the 2.0 branch.
However, I just upgraded and am now in version 2.0.0-DEV, but the option "file.send-compress" is not recognized: h2o won't start, just replying "unknown command: file.send-compress".
The "file.send-gzip" directive is still recognized, though.
Did I miss something while building, or is something missing in the setup files?
Cheers!

**Comment by fetus-hina** [comment]
https://github.com/h2o/h2o/blob/62cf06f9ec047badf7de58c54418fdd5a9d61dcc/lib/handler/configurator/file.c#L182
Looks either the source or the document is incorrect. (in current source, not "compress" but "compress**ed**" )

Note:
This issue was reproduced at my 2.0.0-beta1 build.
https://gist.github.com/fetus-hina/ac919c97784906c03d5d
(You can find my binary via RPM at https://rpm.fetus.jp/h2o-2.0/el7/x86_64/ )
And after rewrite to `file.send-compressed: ON`, looks work well.

**Comment by kazuho** [comment]
@minami-o Thank you for noticing the issue, and @fetus-hina thank you for identifying the cause.

It is a documentation bug, users should use `file.send-compressed`.
