### ISSUE TITLE
cap number of inflight OCSP updaters

### ISSUE THREAD

**Issue by mattparlane** [h2o/h2o#862]
Hi there...

I am using H2O for SSL offloading, and it's mostly working well except I am finding there is a roughly 12-second delay when restarting by sending a HUP to the master process.

I am hosting sites for many customers. I am automatically generating certificates using Let's Encrypt, and writing a configuration file automatically, then sending a HUP if the configuration has changed. I currently have 340 certificates. This process works well, except the server seems to hang until the OCSP process has finished. It may be coincidence, but the length of hang is about the same as the time the OCSP process takes for all of the 340 certs.

I added a file called `time.php`, which contains the line `<?php echo microtime(TRUE); ?>`, and then ran this line:

`while true; do curl https://admin.wb.gs/time.php; done`

which resulted in this output:

    [...]
    1460183091.9597
    1460183092.0913
    1460183092.2192
    1460183092.3519
    1460183092.4796
    1460183104.4357
    1460183104.5715
    1460183104.6887
    1460183104.8206
    1460183104.9432
    [...]

The process hung in the middle for about 12 seconds while the restart took place -- you can see that delay from the numbers.

Any ideas?

Thanks,

Matt

**Comment by kazuho** [comment]
Thank you for raising the issue.

When doing a graceful restart, the old server gets terminated after one second, under the assumption that the initialization of the new worker completes within the time frame.

In your case, it is clear that the server is taking more time - I will look into how we could resolve the issue.

**Comment by mattparlane** [comment]
Brilliant, thanks so much. Please let me know if I can provide any more information.

If the issue is the time it takes to do the OCSP check, one idea I had was to not do the check at startup, and also to randomise the interval -- something like between n/2 and n, where n is the ocsp-update-interval setting. That would avoid the issue of a delay on startup, and it would also avoid stampeding when the interval comes round again.

**Comment by kazuho** [comment]
@mattparlane Looking at the source code, it seems unlikely that the collectors of the OCSP stapling data blocks the server from running.  What you are seeing is likely either of the following:
* setting up the SSL contexts (reading the keypairs and calculating the temporary values) is taking too long
* number of the OCSP stapling collectors (340?) is causing high load on your system, causing a huge delay in the PHP script

Therefore, can you please confirm if the delay is caused by the use of OCSP stapling?  I would appreciate it if you could set `ocsp-update-interval` of the SSL contexts to zero to disable stapling (see https://h2o.examp1e.net/configure/base_directives.html#ocsp-update-interval) and see if the issue still persists.

If it turns out that the cause of the issue is the former, then I think we should support lazy initialization of SSL contexts (i.e. delay the load the certificate / private-key until they get needed). Or if it turns out to be the latter, we should cap the number of OCSP collectors.

**Comment by mattparlane** [comment]
I had already disabled OCSP checking, I used that as a workaround, apologies for not mentioning it earlier. I've just done my test again and there is no perceptible delay when restarting.

The reason I initially thought that the delay was caused by the OCSP checking was that the delay seemed to coincide with the processes running on the server. I was running `ps afx` as it restarted and watching the processes spawn and finish, and once they had all finished the server came back to life.

**Comment by kazuho** [comment]
Thank you for the clarification and testing.  That helps a lot.

So it seems that we need to provide a directive to cap the number of OCSP stapling collectors (a dedicated process is spawned for every TLS certificate), with some modest value set as the default.

**Comment by kazuho** [comment]
@mattparlane Implemented in #891.  Please let me know if you have any issues.

**Comment by mattparlane** [comment]
Brilliant! No measurable slowdown whatsoever.  👍  🍰
