### ISSUE TITLE
Server push with libh2o

### ISSUE THREAD

**Issue by karantin2020** [h2o/h2o#957]
Hi, all.
Help, please. I found in lib `h2o_push_path_in_link_header` use only with proxy handler, fastcgi and mruby.

How to use http/2 server push with libh2o?
Thanks

**Comment by karantin2020** [comment]
Sorry, I found it.
Is it possible to implement `h2o_push_path_in_link_header` in `h2o_file_send` and `h2o_send`?

Or only lib user has to implement it?

**Comment by kazuho** [comment]
You might have already found the answer, but the correct way to do initiate a push from libh2o is to call `req->conn->callbacks->push_path(req, path, path_len)` after chceking that `push_path` is a non-NULL pointer.

> Is it possible to implement `h2o_push_path_in_link_header` in `h2o_file_send` and `h2o_send`?

No, since that is not the ideal way to do it. Generally speaking, you would want to start pushing a response _before_ starting to send the main response.

**Comment by karantin2020** [comment]
Thanks a lot
